version: 2
jobs:
  build:
    working_directory: /build_arch_go
    docker:
      - image: docker:latest
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_USER_PWD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build arch_go images
          command: apk add git jq && ls -lah && pwd && sh build_new_tags.sh

workflows:
  version: 2
  build-on-push:
    jobs:
      - build:
          filters:
            branches:
              only: master
  check_and_build:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
