version: 2
jobs:
  build:
    working_directory: /build_arch_go
    docker:
      - image: docker:18.06.3-ce-git
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_USER_PWD
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build arch_go images
          command: pwd && sh build_new_tags.sh

workflows:
   version: 2
   check_and_build:
     triggers:
       - schedule:
           cron: "15 * * * *"
          #  cron: "0 0 * * 0"
           filters:
            branches:
              only:
                - master
     jobs:
       - build
