name: build-images

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - uses: actions/checkout@v3
      - name: run
        env:
          DOCKER_HUB_USER_ID: ${{ secrets.DOCKER_HUB_USER_ID }}
          DOCKER_HUB_USER_PWD: ${{ secrets.DOCKER_HUB_USER_PWD }}

        run: |
          sudo apt update -y
          sudo apt install -y git jq
          ls -lah
          pwd
          bash build_new_tags.sh
