on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_missing_images:
    runs-on: ubuntu-latest
    steps:
      - name: Run 
        run: ./scripts/build_new_tags.sh
        shell: bash